{
 "title": "HTTP requests metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Average query duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{service=\"pr-manager-service\"}[5m]))\n/\nsum(rate(http_request_duration_seconds_count{service=\"pr-manager-service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method, status) (rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_request_duration_seconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}