{
 "title": "Main Service Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "${VAR_DS_PROMETHEUS}" }
  ]
 },
 "panels": [
  {
   "title": "Go Runtime Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap System memory size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      { "expr": "go_memstats_heap_sys_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Number of heap objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      { "expr": "go_memstats_heap_objects", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Last GC time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "go_memstats_last_gc_time_seconds",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Runtime threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      { "expr": "go_threads", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "GC frequency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds_count[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap allocation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      { "expr": "go_memstats_alloc_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Number of goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      { "expr": "go_goroutines", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "HTTP metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP latency (p95)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(http_request_duration_seconds_bucket{service=\"pr-manager-service\"}[5m])\n  )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Methods RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum by (method) (\n  rate(http_requests_total{service=\"pr-manager-service\"}[1m])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP Requests Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(http_requests_total{service=\"pr-manager-service\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_sum{service=\"pr-manager-service\"}[5m]))\n/\nsum(rate(http_request_duration_seconds_count{service=\"pr-manager-service\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Business metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "pr_manager_teams_created_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "pr_manager_teams_created_total{service=\"pr-manager-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pr_manager_pull_requests_created_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "pr_manager_pull_requests_created_total{service=\"pr-manager-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pr_manager_users_activated_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "pr_manager_users_activated_total{service=\"pr-manager-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pr_manager_pull_requests_merged_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "pr_manager_pull_requests_merged_total{service=\"pr-manager-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pr_manager_users_deactivated_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "pr_manager_users_deactivated_total{service=\"pr-manager-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pr_manager_pull_requests_reassigned_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "pr_manager_pull_requests_reassigned_total{service=\"pr-manager-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}